[2025-03-22T11:37:12.133+0800] {processor.py:186} INFO - Started process (PID=97317) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:37:12.134+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:37:12.134+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:37:12.134+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:37:12.142+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:37:12.142+0800] {dagbag.py:387} ERROR - Failed to import: /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
Traceback (most recent call last):
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 3, in <module>
    from google.cloud import bigquery
ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
[2025-03-22T11:37:12.142+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:37:12.179+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.047 seconds
[2025-03-22T11:38:34.679+0800] {processor.py:186} INFO - Started process (PID=97443) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:38:34.680+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:38:34.680+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:38:34.680+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:38:34.688+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:38:34.687+0800] {dagbag.py:387} ERROR - Failed to import: /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
Traceback (most recent call last):
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 3, in <module>
    from google.cloud import bigquery
ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
[2025-03-22T11:38:34.688+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:38:34.725+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.047 seconds
[2025-03-22T11:39:05.868+0800] {processor.py:186} INFO - Started process (PID=97570) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:39:05.868+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:39:05.869+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:39:05.869+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:39:05.877+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:39:05.876+0800] {dagbag.py:387} ERROR - Failed to import: /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
Traceback (most recent call last):
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 3, in <module>
    from google.cloud import bigquery
ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
[2025-03-22T11:39:05.877+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:39:05.915+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.048 seconds
[2025-03-22T11:42:02.676+0800] {processor.py:186} INFO - Started process (PID=97914) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:42:02.676+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:42:02.676+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:42:02.676+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:42:02.684+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:42:02.684+0800] {dagbag.py:387} ERROR - Failed to import: /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
Traceback (most recent call last):
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 3, in <module>
    from google.cloud import bigquery
ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
[2025-03-22T11:42:02.684+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:42:02.722+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.047 seconds
[2025-03-22T11:42:39.976+0800] {processor.py:186} INFO - Started process (PID=98036) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:42:39.976+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:42:39.977+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:42:39.977+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:42:39.983+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:42:39.983+0800] {dagbag.py:387} ERROR - Failed to import: /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
Traceback (most recent call last):
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 3, in <module>
    from google.cloud import bigquery
ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
[2025-03-22T11:42:39.983+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:42:40.020+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.045 seconds
[2025-03-22T11:43:11.511+0800] {processor.py:186} INFO - Started process (PID=98091) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:11.511+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:43:11.512+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:11.512+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:11.518+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:11.518+0800] {dagbag.py:387} ERROR - Failed to import: /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
Traceback (most recent call last):
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 3, in <module>
    from google.cloud import bigquery
ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
[2025-03-22T11:43:11.518+0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:11.554+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.044 seconds
[2025-03-22T11:43:23.596+0800] {processor.py:186} INFO - Started process (PID=98111) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:23.596+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:43:23.596+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.596+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:23.792+0800] {processor.py:925} INFO - DAG(s) 'transport_dag' retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:23.857+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.857+0800] {override.py:1930} INFO - Created Permission View: can read on DAG:transport_dag
[2025-03-22T11:43:23.860+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.860+0800] {override.py:1930} INFO - Created Permission View: can edit on DAG:transport_dag
[2025-03-22T11:43:23.862+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.862+0800] {override.py:1930} INFO - Created Permission View: can delete on DAG:transport_dag
[2025-03-22T11:43:23.865+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.865+0800] {override.py:1930} INFO - Created Permission View: can read on DAG Run:transport_dag
[2025-03-22T11:43:23.866+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.866+0800] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:transport_dag
[2025-03-22T11:43:23.868+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.868+0800] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:transport_dag
[2025-03-22T11:43:23.870+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.870+0800] {override.py:1930} INFO - Created Permission View: can create on DAG Run:transport_dag
[2025-03-22T11:43:23.870+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.870+0800] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-22T11:43:23.874+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.874+0800] {dag.py:3262} INFO - Creating ORM DAG for transport_dag
[2025-03-22T11:43:23.877+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:23.877+0800] {dag.py:4180} INFO - Setting next_dagrun for transport_dag to 2025-03-21 00:00:00+00:00, run_after=2025-03-22 00:00:00+00:00
[2025-03-22T11:43:23.882+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.288 seconds
[2025-03-22T11:43:28.670+0800] {processor.py:186} INFO - Started process (PID=98186) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:28.670+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:43:28.671+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:28.671+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:28.816+0800] {processor.py:925} INFO - DAG(s) 'transport_dag' retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:43:28.818+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:28.818+0800] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-22T11:43:28.854+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:43:28.854+0800] {dag.py:4180} INFO - Setting next_dagrun for transport_dag to 2025-03-21 00:00:00+00:00, run_after=2025-03-22 00:00:00+00:00
[2025-03-22T11:43:28.860+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.191 seconds
[2025-03-22T11:47:17.339+0800] {processor.py:186} INFO - Started process (PID=98691) to work on /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:47:17.340+0800] {processor.py:914} INFO - Processing file /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py for tasks to queue
[2025-03-22T11:47:17.341+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:47:17.341+0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:47:17.482+0800] {processor.py:925} INFO - DAG(s) 'transport_dag' retrieved from /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py
[2025-03-22T11:47:17.520+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:47:17.520+0800] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-22T11:47:17.526+0800] {logging_mixin.py:190} INFO - [2025-03-22T11:47:17.526+0800] {dag.py:4180} INFO - Setting next_dagrun for transport_dag to 2025-03-22 00:00:00+00:00, run_after=2025-03-23 00:00:00+00:00
[2025-03-22T11:47:17.532+0800] {processor.py:208} INFO - Processing /Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py took 0.194 seconds
